data_root: /users/project1/pt01190/sjs/Segmentacje
output: /users/project1/pt01190/sjs/Results/radiomics_results.csv
mode: null
param_file_3d: 3d_params.yml
param_file_2d: 2d_params.yml
regions: null
label: 1
parallel: false
processes: null
slice_selection: null